### ISSUE TITLE
Issue with modified Ical events

### ISSUE THREAD

**Issue by j-veylop** [emmanueltouzery/cigale#5]
When I modify a calendar event, I get both the old one and the new one. Is there some sort of cache or local config that should be flushed to delete the old one?

**Comment by emmanueltouzery** [comment]
Hmm that's interesting.. There is in fact a cache, but I'm not sure it's to blame. It's easy to check though: you could delete it.

The way the cache works is that Cigale goes to fetch the iCal only if you ask for data newer than the timestamp of the cache. When we start the app, yesterday is displayed by default, so typically the data will be fetched once per day, unless you go checking for data in the future.

If the cache is outdated, it should be ignored and repopulated. The cache should also contain directly data from the server, unprocessed, so it can also help you track down the issue.

And since 0.4.0 the cache is in ~/.cigale/*.cache

The filename will contain "iCal" and your iCal event source name. It used to be called, I think, ical-cache.ical or something of the sort, but that's obsolete now. You can check the timestamp of in doubt.

The cache is not per-day, it contains the whole iCal from the server.

Let me know what you find out! Right now I'd still blame the upstream iCal storage but...

**Comment by j-veylop** [comment]
Indeed, it seems to be upstream iCal, since I not only deleted the cache, but removed the calendar, uninstalled and deleted the whole flatpak folder. Then, after reinstalling, it had the same duplicated event. I guess you can close it, since I don't think there is not much we can do in that case.

**Comment by emmanueltouzery** [comment]
Ok. You can also inspect the cache contents yourself to make sure, iCal is relatively readable. Closing as you said, feel free to reopen if new elements come to light!
