### ISSUE TITLE
gitlab token scope

### ISSUE THREAD

**Issue by zcorniere** [emmanueltouzery/cigale#6]
Bonjour !

What is the expected scope of the gitlab token ?

Currently running Gitlab 12.10.3 with `read_api`, `read_user`, `read_repository` scope and it does not work.

```
[2020-05-11T15:17:18Z ERROR cigale::widgets::events] Fetched events: errors present: Gitlab - [SOURCE NAME]: Can't find all projects?
```

**Comment by emmanueltouzery** [comment]
Bonjour ;)

I'm using `api, read_user`. The call that seems to fail for you is:
https://docs.gitlab.com/ee/api/projects.html

currently trying to find out if there's a way I could reduce the rights. Otherwise yes once we establish what are the correct settings I'll make sure it's documented in the GUI.

**Comment by emmanueltouzery** [comment]
Right, so at my work they have gitlab 12.7 and read_api was introduced with gitlab 12.10. So that's why I'm using it with the full 'api', because i have no other choice.

Now, as to whether your issue is in fact the rights, that's far from sure. In fact most likely that's not the problem, because if you see that error the REST call was already done.

cigale only expects the fields 'id' and 'web_url' to be populated in the REST response. I'll push some debugging in cigale such that if you build it from source (sorry that debugging is not present in the released version) and run it with some environment variables we can see what gitlab returns to you. Maybe the web_url field is not populated? or the id is negative? (i put usize).

**Comment by emmanueltouzery** [comment]
actually there is a simpler way: cigale caches the response from gitlab. You should find the cache in ~/.cigale

If you could give or inspect the contents of this file.. I'm expecting a json array with objects containing at least an id with a positive integer and a web_url string field.

**Comment by zcorniere** [comment]
The file is, indead a json array, with all the required values.
Changing the token scope doesn't seems to change anything. 

EDIT : Actually, with further research some of the projects are not listed in the json file

**Comment by emmanueltouzery** [comment]
yes.. that's the issue. Sorry i was a little slow. When we fetch events with `/api/v4/events`, some events mention a project that we don't find from the list of projects. I'm not sure how could that be.

The code is supposed to refetch if some projects are not found. Maybe check the timestamp of the cache or delete the file, to check whether the projects are in fact refetched. If they get refetched and gitlab doesn't list all the projects, I can make a workaround possibly, but it would be better to understand how does it come to that.

**Comment by emmanueltouzery** [comment]
I googled a little, I may have found the explanation:
https://serverfault.com/questions/570126/using-gitlab-projects-are-missing-from-the-api-list#

They say that the list of projects is paginated and you get only 20 by default. Can you check if you get exactly 20 projects in that cache file? If that's the case then I can probably fix it quickly.

**Comment by zcorniere** [comment]
Yep, exactly 20 projects :)

**Comment by emmanueltouzery** [comment]
I pushed a fix. I'll release on flathub tomorrow. If you're building from git I'm interested if master now works for you. If you're using flathub, you can wait for the new version!

**Comment by zcorniere** [comment]
Hey ! 
Thanks, it seems to be working : no error and the projet is correctly listed !
